version: '3.8'

services: 
  app:
    container_name: godiscoverafrica-web-prod
    image: godiscoverafrica-web-prod
    build: 
      context: .
      target: production
      dockerfile: ./Dockerfile.prod
    ports: 
      - 80:80
